services:
  mysql:
    image: mysql:8
    restart: always
    env_file: .env
    ports:
      - "3310:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      retries: 5
      start_period: 20s  
  app:
    build: .
    env_file: .env
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      mysql:
        condition: service_healthy
volumes:
   db_data: